# Generated by Django 5.1.3 on 2024-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_django_api_rest', '0004_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
