# Generated by Django 5.1.3 on 2024-11-20 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_django_api_rest', '0005_alter_student_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)]),
        ),
    ]
